# Generated by Django 3.1.2 on 2021-01-13 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='address',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='dose',
            field=models.CharField(choices=[('0.5', 'I'), ('1', 'Ii')], default=None, max_length=4),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='full_name',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='gender',
            field=models.CharField(choices=[('male', 'M'), ('female', 'F'), ('others', 'O')], default='male', max_length=8),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='health_info',
            field=models.TextField(default=None, max_length=256),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='password',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='status',
            field=models.CharField(choices=[('Positive', 'P'), ('Negative', 'N')], default='Negative', max_length=10),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='vaccine_group',
            field=models.CharField(choices=[('Group A', 'A'), ('Group B', 'B')], default=None, max_length=8),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='email',
            field=models.EmailField(default=None, max_length=64),
        ),
    ]
