# Generated by Django 3.1.2 on 2021-01-13 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0002_auto_20210113_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='age',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='dose',
            field=models.CharField(choices=[('half', 'Half Dose'), ('full', 'Full Dose')], default=None, max_length=4),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='email',
            field=models.EmailField(default=None, max_length=64, unique=True),
        ),
    ]
