# Generated by Django 3.1.2 on 2021-01-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0005_auto_20210114_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='vaccine_group',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B')], default='A', max_length=8),
        ),
    ]
