# Generated by Django 3.1.2 on 2021-01-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0007_auto_20210114_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default=None, max_length=64, unique=True)),
                ('password', models.CharField(default=None, max_length=64)),
                ('name', models.CharField(default=None, max_length=64)),
                ('age', models.IntegerField(default=None)),
                ('address', models.CharField(default=None, max_length=256)),
            ],
        ),
    ]
